### ISSUE TITLE
[Question] What about websockets to get real-time market data?

### ISSUE THREAD

**Issue by eusonlito** [MockingMagician/coinbase-pro-sdk#15]
Hello! what about methods to get real-time exchange market data?

Thanks!

**Comment by MockingMagician** [comment]
Hi @eusonlito

websocket is mostly ready to run, you can track progress on the feat/websocket branch. Some progress are not already pushed on it, but I can tell you we are so close to a release :wink:

**Comment by eusonlito** [comment]
Great! Thanks!

**Comment by MockingMagician** [comment]
Done ! See 7071bad v0.8.0
