### ISSUE TITLE
Support Symfony 5.x

### ISSUE THREAD

**Issue by spignataro** [MockingMagician/coinbase-pro-sdk#27]
It does not look like the package supports the latest version of Symfony. I haven't tested updating the composer.json file.

**Comment by spignataro** [comment]
Problem 1
    - Root composer.json requires mocking-magician/coinbase-pro-sdk ^0.9.4 -> satisfiable by mocking-magician/coinbase-pro-sdk[v0.9.4].
    - mocking-magician/coinbase-pro-sdk v0.9.4 requires symfony/yaml ^4.0 -> found symfony/yaml[v4.0.0, ..., v4.4.34] but it conflicts with your root composer.json require (5.3.*).


This is the error I receive.

**Comment by MockingMagician** [comment]
Hi @spignataro 

Thaks for the update. I fixed that just a few moments ago, available in last release v0.9.5 - f597eff

Works fine!
