### ISSUE TITLE
OrderData.php post_only must be of the type bool, null given

### ISSUE THREAD

**Issue by jaaloma** [MockingMagician/coinbase-pro-sdk#28]
Hi,

Argument 11 passed to MockingMagician\CoinbaseProSdk\Functional\DTO\OrderData::__construct() must be of the type bool, null given, called in...

For some reason, the Coinbase pro API is returning this null field, and the library expects a bool value.
This is the field: post_only It must be able to be bool? null

Thank you for the bundle.

**Comment by MockingMagician** [comment]
Okay, I will check it tomorrow

**Comment by MockingMagician** [comment]
Hi @jaaloma , I have implemented a fix for that in [last release](https://github.com/MockingMagician/coinbase-pro-sdk/tree/v0.9.6). Can you update and tell me if your case is OK ?

**Comment by jaaloma** [comment]
Hi,

Are you going to migrate to the new API (Advanced Trade API) Early 2023 PRO
API doesn't work.

**Comment by jaaloma** [comment]
Hi,

Are you going to migrate to the new API (Advanced Trade API) Early 2023 PRO
API doesn't work.

>
