### ISSUE TITLE
Products Api Not working its shows error

### ISSUE THREAD

**Issue by robod9590** [MockingMagician/coinbase-pro-sdk#33]
$api = CoinbaseFacade::createDefaultCoinbaseApi($endpoint, $api_key, $api_secret, $passphrase);

//APis

$api->products()->getProducts('BTC-USD');

$api->products()->getSingleProduct('BTC-USD');

Error:
"message": "Undefined array key \"base_min_size\"",

file": "vendor\\mocking-magician\\coinbase-pro-sdk\\src\\Functional\\DTO\\ProductData.php",

**Comment by MockingMagician** [comment]
Hi @robod9590, fix has been pushed about your issue. You can update your package to the latest version.

See you !
